name: build

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '0 1 * * 0'
  workflow_dispatch:

env:
  NEXTCLOUD_VERSION: 26
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: ${{ github.repository }}-full-fpm


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout upstream files
      run: |
        git clone --depth 1 https://github.com/nextcloud/docker.git repo
        mv repo/.examples/dockerfiles/full/fpm/Dockerfile Dockerfile-full-fpm
        mv repo/.examples/dockerfiles/full/fpm/supervisord.conf supervisord.conf
        rm -r repo
        sed -i 's/nextcloud:fpm/nextcloud:${{ env.NEXTCLOUD_VERSION }}-fpm/g' Dockerfile-full-fpm
        
    - name: Commit updates
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "workflow@github.com"
          git config --local user.name "GitHub Workflow"
          git add -A
          git commit -m "Apply updates from Nextcloud repository"
        fi
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@main

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build upstream full fpm image from Nextcloud repository
      - name: Extract Docker metadata
        id: meta-upstream
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}
          tags: |
            latest
            ${{ env.NEXTCLOUD_VERSION }}

      - name: Build and push Docker image
        id: build-and-push-upstream
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-full-fpm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-upstream.outputs.tags }}
          labels: ${{ steps.meta-upstream.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta-upstream.outputs.tags }}" | xargs -I {} cosign sign -y {}@${{ steps.build-and-push-upstream.outputs.digest }}
